project:
  name: "srv example"
  version: "0.0.1"
  debug: true
  environment: "development"
log:
  level: "debug"
  output_format: "text"
  write_to_file: false
  path: "var/log/app.log"
server:
  host: ""
  port: 8080
  read_header_timeout: 5s
  write_timeout: 30s
  idle_timeout: 30s
grpc_server:
  endpoint: ":50051"
  api_endpoint: "/api/v1/"
cors:
  allowed_origins:
    - "http://localhost:3000"
